### ISSUE TITLE
Mnemonic seed

### ISSUE THREAD

**Issue by cockerfly** [alwaysminingbtc/plutushybid#5]
Help me, please

Traceback (most recent call last):
  File "plutushybrid.py", line 2, in <module>
    import mnemonic
ModuleNotFoundError: No module named 'mnemonic'

"pip install mnemonic" don't help me

**Comment by ZaranTheWise** [comment]
what happened after you tried pip install mnemonic?

**Comment by cockerfly** [comment]
> 
> 
> what happened after you tried pip install mnemonic?

Traceback (most recent call last):
  File "plutushybrid.py", line 3, in <module>
    import bip32utils
ModuleNotFoundError: No module named 'bip32utils'

**Comment by ZaranTheWise** [comment]
pip install bip32utils
