### ISSUE TITLE
Error 'Ran out of input'

### ISSUE THREAD

**Issue by RastaDollo** [alwaysminingbtc/plutushybid#9]
reading database: 12/12 DONE
Traceback (most recent call last):
  File "C:\Python\plutushybrid\plutushybrid.py", line 112, in <module>
    multiprocessing.Process(target = main, args = (database, )).start()
  File "C:\Python\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Python\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init_
_
    reduction.dump(process_obj, to_child)
  File "C:\Python\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
MemoryError
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Python\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

Windows XP,Atom proccesor, Python 3.4.3
I don't understand what the problem ?
Maybe old proccesor of old windows ?

**Comment by mjnowak1982** [comment]
I'm having the same issues
